services:
  app:
    build: ./application
    container_name: mychat
    environment:
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=admin
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=chat_database
      - BOT_TOKEN=8001877737:AAE-ksWZ7kiTqkdQWq6D9_xUGwuU9BJbfB8

    ports:
      - "8000:8000"
    networks:
      - app_network
    depends_on:
      postgres:
        condition: service_healthy

  bot:
    build: ./bot
    container_name: mychat_bot
    environment:
      - BOT_TOKEN=8001877737:AAE-ksWZ7kiTqkdQWq6D9_xUGwuU9BJbfB8
      - MYCHAT_URL=http://app:8000
    networks:
      - app_network


  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=chat_database
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d chat_database" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
